### PR TITLE
widevine: add required service, rc and lib

### PR DESCRIPTION
**Pull request by oshmoun**

### CODE REVIEW

**Comment by oshmoun** [comment]
Could this please be tested on an msm8974 device?
to include this:
$(call inherit-product, vendor/sony/widevine/widevine.mk)

the app "DRM Info" should show if widevine support is detected

**Comment by nailyk-fr** [comment]
There is a crash. But it could be related to missing gapps:
[wv.log](https://github.com/DonkeyCoyote/proprietary_vendor_sony/files/1628342/wv.log)
Otherwise build fine. 
Patchs uploaded to gerrit: https://gerrit.nailyk.fr/#/c/1118/ & https://gerrit.omnirom.org/#/c/28279/ for the CI.

**Comment by oshmoun** [comment]
Thanks for testing!
Then these are probably incompatible with 8974
Will test here without gapps just to make sure though

**Comment by nailyk-fr** [comment]
No problem :)
You can add patches to my builds by pushing on jenkins-scripts on my gerrit (like this: https://gerrit.nailyk.fr/#/c/1076/ )
They will be picked by jenkins, then shinano & oneplus5t will have it.

**Pull request merged**
