### PR TITLE
Sony AOSP: Up to Android M v05

### PR DESCRIPTION
**Pull request by humberos**
Signed-off-by: Humberto Borba humberos@gmail.com

### CODE REVIEW

**Comment by humberos** [comment]
ping @erikcas , @olivieer

**Comment by erikcas** [comment]
building sumire amami eagle

**Comment by humberos** [comment]
ok, rhine mba files are back :P

**Comment by humberos** [comment]
Is it ok to go?

**Comment by erikcas** [comment]
Tested oke so as far as I am concerned good to go

**Comment by Incredible-O** [comment]
Can't test right now, but that sure won't break ivy, given it works on sumire and karin

**Comment by humberos** [comment]
Ok! Thank you!

**Pull request merged**
